show_downloads: true
download_android: false
remote_theme: logzinga/cayman-hatrunner2

github:
  zip_url: https://github.com/logzinga/HatGunner/releases/download/v0.3/Windows.zip
  tar_url: https://github.com/logzinga/HatGunner/releases/download/v0.3/Linux.tar.gz
