show_downloads: true
download_android: false
remote_theme: logzinga/cayman-hatrunner2

github:
  zip_url: https://github.com/logzinga/HatGunner/releases/download/v1.0/Windows.v1.0.zip
  tar_url: https://github.com/logzinga/HatGunner/releases/download/v1.0/Linux.v1.0.tar.gz
